In [1]:
import torch

In [16]:
x=torch.arange(4.0)
x.requires_grad=True

In [17]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [18]:
y.backward()

In [20]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
x.grad==4*x

tensor([True, True, True, True])

In [27]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [23]:
x.grad

tensor([0., 0., 0., 0.])

In [29]:
y.grad_fn